openapi: 3.0.3
info:
  title: Bot-API-Gateway
  description: Gateway oficial con filtrado de rutas y seguridad
  version: 1.0.4
servers:
  - url: https://bots-gateway-prod-83hfw8tp.ew.gateway.dev
paths:
  /:
    get:
      operationId: dashboardAccess
      x-google-backend:
        address: https://bot-service-634498283437.europe-southwest1.run.app/
      responses:
        '200':
          description: OK

  '/{proxy+}':
    parameters:
      - name: proxy
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: apiProxyGet
      x-google-backend:
        address: https://bot-service-634498283437.europe-southwest1.run.app/{proxy}
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
    post:
      operationId: apiProxyPost
      x-google-backend:
        address: https://bot-service-634498283437.europe-southwest1.run.app/{proxy}
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK